# Generated by Django 3.2.8 on 2021-10-21 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPreliminary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CheckPreliminaryFileToCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='preliminary_check/to_check')),
                ('check_preliminary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.checkpreliminary')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EZdoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateField()),
                ('max_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('decision', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='EZ/doc')),
                ('signed_bool', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=100)),
                ('date_of_appliance', models.DateField()),
                ('sun_of_appliance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('pp', models.CharField(max_length=10)),
                ('type', models.TextField(blank=True, null=True)),
                ('responsible_after_temp_stop', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='responsible_after_temp_stop', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_IAS', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notification_sent_date', models.DateField(blank=True, null=True)),
                ('end_date_for_remade_order', models.DateField(blank=True, null=True)),
                ('remade_order_received', models.DateField(blank=True, null=True)),
                ('end_date_after_temp_stop', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_preliminary', models.BooleanField(default=True)),
                ('is_refuse_by_date', models.BooleanField(blank=True, null=True)),
                ('date_IAS', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notification_sent_date', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCalledBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTempStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notification_date', models.DateField()),
                ('notification_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sent_to_applier_date', models.DateField(blank=True, null=True)),
                ('temp_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.tempstop')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRefuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('notification_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sent_to_applier_date', models.DateField(blank=True, null=True)),
                ('refuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.refuse')),
            ],
        ),
        migrations.CreateModel(
            name='LotkiTempStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_received', models.DateField()),
                ('date_signed', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotkiRefuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_received', models.DateField()),
                ('date_signed', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotkiEZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_received', models.DateField()),
                ('date_signed', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EZpdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='EZ/pdf')),
                ('ez_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.ezdoc')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ezdoc',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order'),
        ),
        migrations.AddField(
            model_name='ezdoc',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CheckPreliminaryResponsibleExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('end_date_for_expert', models.DateField()),
                ('check_preliminary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.checkpreliminary')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckPreliminaryFileToCheckReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='preliminary_check/returned')),
                ('check_preliminary_file_to_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.checkpreliminaryfiletocheck')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckPreliminaryFileToCheckFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='preliminary_check/final')),
                ('check_preliminary_file_to_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.checkpreliminaryfiletocheck')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checkpreliminary',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order'),
        ),
        migrations.AddField(
            model_name='checkpreliminary',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Applier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('applier_company', models.CharField(max_length=200)),
                ('applier_company_inn', models.CharField(max_length=20)),
                ('applier_email', models.CharField(max_length=50)),
                ('applier_tel', models.CharField(max_length=20)),
                ('applier_fio', models.CharField(max_length=200)),
                ('category', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.order')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
