# Generated by Django 3.2.8 on 2021-10-22 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefuseReasonsAfterTempStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('common_reason', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RefuseReasonsPreliminary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('common_reason', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='tempstop',
            old_name='remade_order_received',
            new_name='end_date_after_temp_stop_for_responsible',
        ),
        migrations.AddField(
            model_name='order',
            name='end_date_for_responsible',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='marked_for_remake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='onsite_check',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='responsible_preliminary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='responsible_preliminary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tempstop',
            name='remade_order_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempstop',
            name='remade_order_sent_to_subcontractor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.CreateModel(
            name='CheckAfterTempStopResponsibleExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('end_date_for_expert', models.DateField()),
                ('check_preliminary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.checkpreliminary')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckAfterTempStopFileToCheckReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='after_temp_stop_check/returned')),
                ('check_preliminary_file_to_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.checkpreliminaryfiletocheck')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckAfterTempStopFileToCheckFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='after_temp_stop_check/final')),
                ('check_preliminary_file_to_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.checkpreliminaryfiletocheck')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckAfterTempStopFileToCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='after_temp_stop_check/to_check')),
                ('check_preliminary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.checkpreliminary')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckAfterTempStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
