# Generated by Django 3.2.8 on 2021-10-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20211025_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
