# Generated by Django 3.2.8 on 2021-10-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_alter_order_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applier',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
