# Generated by Django 3.2.8 on 2021-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_alter_applier_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='applier',
            name='applier_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
