# Generated by Django 3.2.8 on 2021-10-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_applier_applier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuse',
            name='is_preliminary',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
