# Generated by Django 3.2.8 on 2021-10-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_auto_20211025_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refusereasonsaftertempstop',
            name='pp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.ppnumber', verbose_name='Номер постановления'),
        ),
        migrations.AlterField(
            model_name='refusereasonspreliminary',
            name='pp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.ppnumber', verbose_name='Номер постановления'),
        ),
    ]
