# Generated by Django 3.2.8 on 2021-10-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_categoriesbyorder_category_senttocorrection_statuschange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applier',
            name='applier_company',
        ),
        migrations.RemoveField(
            model_name='applier',
            name='applier_company_inn',
        ),
        migrations.AddField(
            model_name='order',
            name='applier_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='applier_company_inn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
