# Generated by Django 3.2.8 on 2021-10-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_auto_20211028_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='applier_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='applier_company_inn',
            new_name='company_inn',
        ),
    ]
