# Generated by Django 3.2.8 on 2021-10-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_responsiblefororderaftertempstop_responsiblefororderpreliminary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='responsible_after_temp_stop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='responsible_preliminary',
        ),
    ]
