# Generated by Django 3.2.8 on 2021-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_auto_20211028_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotkiContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
