# Generated by Django 3.2.8 on 2021-10-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_lotkicontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lotki_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.lotkicontent'),
        ),
    ]
