# Generated by Django 3.2.8 on 2021-10-29 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0023_alter_ordertypecheck_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpreliminary',
            name='type',
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckfinal',
            name='responsible_expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='aftertempstop_check_files_final_responsible_expert', to='dash.checkaftertempstopresponsibleexpert'),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckreturned',
            name='responsible_expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='aftertempstop_check_files_returned_responsible_expert', to='dash.checkaftertempstopresponsibleexpert'),
        ),
        migrations.AddField(
            model_name='checkaftertempstopresponsibleexpert',
            name='responsible_expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='aftertempstop_check_responsible_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkpreliminaryfiletocheckfinal',
            name='responsible_expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='preliminary_check_files_final_responsible_expert', to='dash.checkpreliminaryresponsibleexpert'),
        ),
        migrations.AddField(
            model_name='checkpreliminaryfiletocheckreturned',
            name='responsible_expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='preliminary_check_files_returned_responsible_expert', to='dash.checkpreliminaryresponsibleexpert'),
        ),
        migrations.AddField(
            model_name='checkpreliminaryresponsibleexpert',
            name='responsible_expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='preliminary_check_responsible_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkaftertempstopresponsibleexpert',
            name='check_preliminary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.checkaftertempstop'),
        ),
        migrations.AlterField(
            model_name='checkpreliminaryresponsibleexpert',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='preliminary_check_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
