# Generated by Django 3.2.8 on 2021-10-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0032_auto_20211029_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lotki_date_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lotki_date_signed',
        ),
        migrations.AlterField(
            model_name='ordertypecheck',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
