# Generated by Django 3.2.8 on 2021-10-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0033_auto_20211029_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lotki_date_received',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lotki_date_signed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
