# Generated by Django 3.2.8 on 2021-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0034_auto_20211029_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesbyorder',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
