# Generated by Django 3.2.8 on 2021-11-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0036_auto_20211102_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lotki_date_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lotki_date_signed',
        ),
        migrations.AddField(
            model_name='lotkirefuse',
            name='date_EZ',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='checkaftertempstop',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkaftertempstopfiletocheck',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkaftertempstopfiletocheckreturned',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkaftertempstopresponsibleexpert',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkpreliminary',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkpreliminaryfiletocheck',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkpreliminaryfiletocheckreturned',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkpreliminaryresponsibleexpert',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ezdoc',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ezpdf',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lotkiez',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lotkirefuse',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lotkitempstop',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationrefuse',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationtempstop',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordercalledback',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='refuse',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tempstop',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
