# Generated by Django 3.2.8 on 2021-11-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0037_auto_20211103_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotkirefuse',
            name='date_signed',
            field=models.DateField(null=True),
        ),
    ]
