# Generated by Django 3.2.8 on 2021-11-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0038_alter_lotkirefuse_date_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotkiez',
            name='date_signed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lotkitempstop',
            name='date_signed',
            field=models.DateField(null=True),
        ),
    ]
