# Generated by Django 3.2.8 on 2021-11-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0040_auto_20211103_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_EZ',
            field=models.DateField(default=None, null=True),
        ),
    ]
