# Generated by Django 3.2.8 on 2021-11-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0045_order_date_ez'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_EZ',
        ),
        migrations.AlterField(
            model_name='applier',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order'),
        ),
        migrations.AlterField(
            model_name='responsiblefororderaftertempstop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order'),
        ),
        migrations.AlterField(
            model_name='responsiblefororderpreliminary',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order'),
        ),
    ]
