# Generated by Django 3.2.8 on 2021-11-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0048_auto_20211103_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_EZ',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lotki_refuse_date_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lotki_refuse_date_signed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lotki_temp_stop_date_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lotki_temp_stop_date_signed',
        ),
    ]
