# Generated by Django 3.2.8 on 2021-11-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0050_auto_20211103_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpreliminary',
            name='order_type_check',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.ordertypecheck'),
        ),
        migrations.AlterField(
            model_name='categoriesbyorder',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.order'),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.order'),
        ),
    ]
