# Generated by Django 3.2.8 on 2021-11-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0051_auto_20211103_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lotki_refuse_date_received',
            new_name='lotki_preliminary_refuse_date_received',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lotki_refuse_date_signed',
            new_name='lotki_preliminary_refuse_date_signed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lotki_temp_stop_date_received',
            new_name='lotki_preliminary_temp_stop_date_received',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lotki_temp_stop_date_signed',
            new_name='lotki_preliminary_temp_stop_date_signed',
        ),
    ]
