# Generated by Django 3.2.8 on 2021-11-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0054_auto_20211103_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrefuse',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.order'),
        ),
        migrations.AlterField(
            model_name='notificationtempstop',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.order'),
        ),
    ]
