# Generated by Django 3.2.8 on 2021-11-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0055_auto_20211103_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_EZ',
            field=models.DateField(default=None, null=True, verbose_name='Дата составления ЭЗ'),
        ),
    ]
