# Generated by Django 3.2.8 on 2021-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0056_alter_order_date_ez'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refuse_is_preliminary',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refuse_is_refuse_by_date',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
