# Generated by Django 3.2.8 on 2021-11-09 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0057_auto_20211108_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefuseReasonsPreliminaryByOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order')),
                ('refuse_reason', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.refusereasonspreliminary')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
