# Generated by Django 3.2.8 on 2021-11-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0058_refusereasonspreliminarybyorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='temp_stop',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
