# Generated by Django 3.2.8 on 2021-11-10 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0059_order_temp_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_orders_to_check_preliminary', models.IntegerField()),
                ('check_orders_checked_preliminary', models.IntegerField()),
                ('check_orders_to_check_after_temp_stop', models.IntegerField()),
                ('check_orders_checked_after_temp_stop', models.IntegerField()),
                ('new_orders', models.IntegerField()),
                ('temp_stop_date', models.IntegerField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
