# Generated by Django 3.2.8 on 2021-11-10 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0060_counters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counters',
            name='id',
        ),
        migrations.AddField(
            model_name='counters',
            name='ez_doc',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='ez_doc_remake',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='ez_pdf',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='refuse_by_date',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='refuse_by_docs',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='refuse_preliminary',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='temp_stop_check',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='temp_stop_on_check',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='temp_stop_remade_order_date',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='temp_stop_remade_order_decision',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='temp_stop_with_notification',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='temp_stop_without_notification',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='counters',
            name='check_orders_checked_after_temp_stop',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='counters',
            name='check_orders_checked_preliminary',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='counters',
            name='check_orders_to_check_after_temp_stop',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='counters',
            name='check_orders_to_check_preliminary',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='counters',
            name='new_orders',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='counters',
            name='temp_stop_date',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='counters',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
