# Generated by Django 3.2.8 on 2021-11-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0061_auto_20211110_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='statist_ez',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='statist_ez_on_signing',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='statist_refuse_on_signing',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='statist_refuses_not_preliminary',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='counters',
            name='statist_temp_stop_on_signing',
            field=models.IntegerField(default=None),
        ),
    ]
