# Generated by Django 3.2.8 on 2021-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0063_auto_20211110_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtempstop',
            name='sent_to_applier_date',
        ),
        migrations.AddField(
            model_name='tempstop',
            name='end_date_for_notification',
            field=models.DateField(blank=True, null=True),
        ),
    ]
