# Generated by Django 3.2.8 on 2021-11-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0066_auto_20211110_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='new_orders_check_is_needed',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
