# Generated by Django 3.2.8 on 2021-11-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0068_auto_20211111_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='temp_stop_remade_order_decision',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
