# Generated by Django 3.2.8 on 2021-11-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0070_auto_20211111_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempstop',
            name='file_notification',
        ),
        migrations.RemoveField(
            model_name='tempstop',
            name='file_pez',
        ),
    ]
