# Generated by Django 3.2.8 on 2021-11-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0074_auto_20211111_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempstop',
            name='file_notification',
        ),
        migrations.RemoveField(
            model_name='tempstop',
            name='file_pez',
        ),
        migrations.CreateModel(
            name='TempStopFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pez', models.FileField(default=None, null=True, upload_to='temp_stop')),
                ('file_notification', models.FileField(default=None, null=True, upload_to='temp_stop')),
                ('temp_stop', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.tempstop')),
            ],
        ),
    ]
