# Generated by Django 3.2.8 on 2021-11-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0075_auto_20211111_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempstop',
            name='end_date_after_temp_stop_for_subcontractor',
            field=models.DateField(blank=True, null=True),
        ),
    ]
