# Generated by Django 3.2.8 on 2021-11-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0077_remove_tempstop_end_date_after_temp_stop_for_subcontractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lotki_preliminary_refuse_date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lotki_preliminary_refuse_date_signed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lotki_preliminary_temp_stop_date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lotki_preliminary_temp_stop_date_signed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
