# Generated by Django 3.2.8 on 2021-11-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0081_refusereasonsaftertempstopbyorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuse',
            name='file',
            field=models.FileField(default=None, upload_to='refuse'),
        ),
    ]
