# Generated by Django 3.2.8 on 2021-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0082_refuse_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuse',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='refuse'),
        ),
    ]
