# Generated by Django 3.2.8 on 2021-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0083_alter_refuse_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refuse',
            old_name='file',
            new_name='file_ez',
        ),
        migrations.AddField(
            model_name='refuse',
            name='file_notification',
            field=models.FileField(default=None, null=True, upload_to='refuse'),
        ),
    ]
