# Generated by Django 3.2.8 on 2021-11-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0084_auto_20211116_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refuse',
            name='file_ez',
        ),
        migrations.RemoveField(
            model_name='refuse',
            name='file_notification',
        ),
    ]
