# Generated by Django 3.2.8 on 2021-11-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0086_auto_20211116_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refuse',
            name='file_ez',
        ),
        migrations.RemoveField(
            model_name='refuse',
            name='file_notification',
        ),
        migrations.CreateModel(
            name='RefuseFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ez', models.FileField(default=None, null=True, upload_to='refuse')),
                ('file_notification', models.FileField(default=None, null=True, upload_to='refuse')),
                ('refuse', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.refuse')),
            ],
        ),
    ]
