# Generated by Django 3.2.8 on 2021-11-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0087_auto_20211116_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lotki_preliminary_refuse_date_received',
            new_name='lotki_after_temp_stop_refuse_date_received',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lotki_preliminary_refuse_date_signed',
            new_name='lotki_after_temp_stop_refuse_date_signed',
        ),
    ]
