# Generated by Django 3.2.8 on 2021-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0088_auto_20211116_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotkicontent',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
