# Generated by Django 3.2.8 on 2021-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0090_auto_20211116_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountersLotki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role_name', models.CharField(default='Статистика (лотки)', max_length=50)),
                ('statist_refuses_not_preliminary', models.IntegerField(default=0, null=True)),
                ('statist_ez', models.IntegerField(default=0, null=True)),
                ('statist_temp_stop_on_signing', models.IntegerField(default=0, null=True)),
                ('statist_refuse_on_signing', models.IntegerField(default=0, null=True)),
                ('statist_ez_on_signing', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='counters',
            name='statist_ez',
        ),
        migrations.RemoveField(
            model_name='counters',
            name='statist_ez_on_signing',
        ),
        migrations.RemoveField(
            model_name='counters',
            name='statist_refuse_on_signing',
        ),
        migrations.RemoveField(
            model_name='counters',
            name='statist_refuses_not_preliminary',
        ),
        migrations.RemoveField(
            model_name='counters',
            name='statist_temp_stop_on_signing',
        ),
    ]
