# Generated by Django 3.2.8 on 2021-11-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0091_auto_20211117_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountersAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role_name', models.CharField(default='Админ', max_length=50)),
                ('admin_orders_all', models.IntegerField(default=0, null=True)),
                ('admin_remade_order_date', models.IntegerField(default=0, null=True)),
                ('admin_distribution_preliminary', models.IntegerField(default=0, null=True)),
                ('admin_distribution_afetr_temp_stop', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='counters',
            name='admin_distribution_afetr_temp_stop',
        ),
        migrations.RemoveField(
            model_name='counters',
            name='admin_distribution_preliminary',
        ),
        migrations.RemoveField(
            model_name='counters',
            name='admin_orders_all',
        ),
        migrations.RemoveField(
            model_name='counters',
            name='admin_remade_order_date',
        ),
    ]
