# Generated by Django 3.2.8 on 2021-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0092_auto_20211117_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='countersadmin',
            name='new_orders_check_is_needed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
