# Generated by Django 3.2.8 on 2021-11-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0093_countersadmin_new_orders_check_is_needed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countersadmin',
            old_name='new_orders_check_is_needed',
            new_name='new_orders',
        ),
    ]
