# Generated by Django 3.2.8 on 2021-11-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0095_auto_20211117_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refuse_after_temp_stop',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
