# Generated by Django 3.2.8 on 2021-11-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0097_lotkistatuschange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countersadmin',
            old_name='admin_distribution_afetr_temp_stop',
            new_name='admin_distribution_after_temp_stop',
        ),
    ]
