# Generated by Django 3.2.8 on 2021-11-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0101_auto_20211122_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpreliminaryfiletocheck',
            name='file',
        ),
        migrations.RemoveField(
            model_name='checkpreliminaryfiletocheckfinal',
            name='file',
        ),
        migrations.RemoveField(
            model_name='checkpreliminaryfiletocheckreturned',
            name='file',
        ),
        migrations.AddField(
            model_name='checkpreliminaryfiletocheck',
            name='file_1',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
        migrations.AddField(
            model_name='checkpreliminaryfiletocheck',
            name='file_2',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
        migrations.AddField(
            model_name='checkpreliminaryfiletocheckfinal',
            name='file_1',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
        migrations.AddField(
            model_name='checkpreliminaryfiletocheckfinal',
            name='file_2',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
        migrations.AddField(
            model_name='checkpreliminaryfiletocheckreturned',
            name='file_1',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
        migrations.AddField(
            model_name='checkpreliminaryfiletocheckreturned',
            name='file_2',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
    ]
