# Generated by Django 3.2.8 on 2021-11-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0104_auto_20211122_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='countersadmin',
            name='all_orders',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
