# Generated by Django 3.2.8 on 2021-11-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0106_auto_20211123_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpreliminaryresponsibleexpert',
            name='end_date_for_expert',
            field=models.DateField(default=None, null=True),
        ),
    ]
