# Generated by Django 3.2.8 on 2021-11-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0110_tempstop_remade_order_subcontractor_end_date_for_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempstop',
            name='remade_order_subcontractor_end_date_for_docs',
        ),
    ]
