# Generated by Django 3.2.8 on 2021-11-26 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0111_remove_tempstop_remade_order_subcontractor_end_date_for_docs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkaftertempstopresponsibleexpert',
            old_name='check_preliminary',
            new_name='check_after_temp_stop',
        ),
        migrations.RemoveField(
            model_name='checkaftertempstopfiletocheck',
            name='check_preliminary',
        ),
        migrations.RemoveField(
            model_name='checkaftertempstopfiletocheck',
            name='file',
        ),
        migrations.RemoveField(
            model_name='checkaftertempstopfiletocheckfinal',
            name='check_preliminary_file_to_check',
        ),
        migrations.RemoveField(
            model_name='checkaftertempstopfiletocheckfinal',
            name='file',
        ),
        migrations.RemoveField(
            model_name='checkaftertempstopfiletocheckfinal',
            name='responsible_expert',
        ),
        migrations.RemoveField(
            model_name='checkaftertempstopfiletocheckreturned',
            name='check_preliminary_file_to_check',
        ),
        migrations.RemoveField(
            model_name='checkaftertempstopfiletocheckreturned',
            name='file',
        ),
        migrations.RemoveField(
            model_name='checkaftertempstopfiletocheckreturned',
            name='responsible_expert',
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheck',
            name='check_after_temp_stop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.checkaftertempstop'),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheck',
            name='file_1',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheck',
            name='file_2',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckfinal',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckfinal',
            name='check_after_temp_stop_file_to_check',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.checkaftertempstopfiletocheck'),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckfinal',
            name='file_1',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckfinal',
            name='file_2',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckfinal',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckreturned',
            name='check_after_temp_stop_file_to_check',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.checkaftertempstopfiletocheck'),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckreturned',
            name='file_1',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
        migrations.AddField(
            model_name='checkaftertempstopfiletocheckreturned',
            name='file_2',
            field=models.FileField(default=None, upload_to='preliminary_check/to_check'),
        ),
        migrations.AlterField(
            model_name='checkaftertempstopresponsibleexpert',
            name='end_date_for_expert',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkaftertempstopresponsibleexpert',
            name='responsible_expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='after_temp_stop_check_responsible_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkaftertempstopresponsibleexpert',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='after_temp_stop_check_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
