# Generated by Django 3.2.8 on 2021-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0113_order_check_preliminary_pass_without_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_after_temp_stop_pass_without_check',
            field=models.BooleanField(default=False, verbose_name='Проверка после возобновления пропущена'),
        ),
    ]
