# Generated by Django 3.2.8 on 2021-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0114_order_check_after_temp_stop_pass_without_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_after_temp_stop_last_date_sent_for_check',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата отправки документов на проверку'),
        ),
        migrations.AddField(
            model_name='order',
            name='check_preliminary_last_date_sent_for_check',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата отправки документов на проверку'),
        ),
    ]
