# Generated by Django 3.2.8 on 2021-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0115_auto_20211129_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='check_after_temp_stop_last_date_sent_for_check',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отправки документов на проверку'),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_preliminary_last_date_sent_for_check',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отправки документов на проверку'),
        ),
    ]
