# Generated by Django 3.2.8 on 2021-11-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0116_auto_20211129_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_after_temp_stop_finals_files_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
