# Generated by Django 3.2.8 on 2021-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0117_order_check_after_temp_stop_finals_files_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_after_temp_stop_returned_after_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='check_preliminary_returned_after_correction',
            field=models.BooleanField(default=False),
        ),
    ]
