# Generated by Django 3.2.8 on 2021-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0119_remove_order_check_after_temp_stop_files_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='applier',
            name='inn',
            field=models.IntegerField(default=None, max_length=20, null=True),
        ),
    ]
