# Generated by Django 3.2.8 on 2021-11-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0121_remove_applier_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsiblefororderaftertempstop',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responsiblefororderpreliminary',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
