# Generated by Django 3.2.8 on 2021-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0125_notificationrefuse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='callback_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отзыва заявки'),
        ),
    ]
