# Generated by Django 3.2.8 on 2021-12-07 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0127_countersadmin_admin_ready_for_ok'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyForOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateField()),
                ('max_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('decision', models.BooleanField(default=False)),
                ('doc_file', models.FileField(upload_to='EZ/doc')),
                ('pdf_file', models.FileField(upload_to='EZ/doc')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.order')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
