# Generated by Django 3.2.8 on 2021-12-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0128_readyforok'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_after_temp_stop_refuse_by_date',
            field=models.BooleanField(default=False, verbose_name='Требуется проверка отказа по сроку после возобновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_after_temp_stop_refuse',
            field=models.BooleanField(default=False, verbose_name='Требуется проверка отказа по документам после возобновления'),
        ),
    ]
