# Generated by Django 3.2.8 on 2021-12-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0129_auto_20211208_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='onsite_check',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выездная проверка'),
        ),
    ]
