# Generated by Django 3.2.8 on 2021-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0130_auto_20211208_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
