# Generated by Django 3.2.8 on 2021-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0131_order_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remade_order_received_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='temp_stop_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
