# Generated by Django 3.2.8 on 2021-12-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0134_readyforok_marked_for_next_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointedforok',
            name='ready_for_OK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.readyforok'),
        ),
    ]
