# Generated by Django 3.2.8 on 2021-12-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0135_appointedforok_ready_for_ok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointedforok',
            old_name='creation_date',
            new_name='ok_date',
        ),
        migrations.RemoveField(
            model_name='appointedforok',
            name='order',
        ),
    ]
