# Generated by Django 3.2.8 on 2021-12-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0136_auto_20211210_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissiondate',
            name='commission',
        ),
        migrations.AddField(
            model_name='appointedforok',
            name='commission_date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.commissiondate'),
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
