# Generated by Django 3.2.8 on 2021-12-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0137_auto_20211210_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointedforok',
            name='ok_date',
        ),
    ]
