# Generated by Django 3.2.8 on 2021-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0138_remove_appointedforok_ok_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyforok',
            name='appointed_ok',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
