# Generated by Django 3.2.8 on 2021-12-10 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0140_countersadmin_appointed_for_ok'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('max_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('decision', models.BooleanField(default=False)),
                ('protocol_date', models.DateField(blank=True, null=True)),
                ('protocol_number', models.IntegerField(default=0, null=True)),
                ('appointed_for_ok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.appointedforok')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
