# Generated by Django 3.2.8 on 2021-12-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0145_auto_20211213_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readyforok',
            name='marked_for_next_ok',
            field=models.BooleanField(default=False),
        ),
    ]
