# Generated by Django 3.2.8 on 2021-12-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0146_alter_readyforok_marked_for_next_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyforok',
            name='onsite_check_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
