# Generated by Django 3.2.8 on 2021-12-13 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0148_auto_20211213_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolok',
            name='protocol_date',
        ),
        migrations.RemoveField(
            model_name='protocolok',
            name='protocol_number',
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('protocol_date', models.DateField(blank=True, null=True)),
                ('protocol_number', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='protocolok',
            name='protocol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.protocol'),
        ),
    ]
