# Generated by Django 3.2.8 on 2021-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0150_auto_20211213_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='countersadmin',
            name='admin_protocols_orders',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
