# Generated by Django 3.2.8 on 2021-10-20 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20)),
                ('email_sent_register_notification', models.BooleanField(default=False)),
                ('common_check_needed', models.BooleanField(default=False)),
                ('check_preliminary_refuse', models.BooleanField(default=False)),
                ('check_preliminary_ez', models.BooleanField(default=False)),
                ('check_preliminary_temp_stop', models.BooleanField(default=False)),
                ('check_after_temp_stop_refuse', models.BooleanField(default=False)),
                ('check_after_temp_stop_ez', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
