# Generated by Django 3.2.8 on 2021-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='check_after_temp_stop_ez',
            field=models.BooleanField(default=False, verbose_name='Требуется проверка ЭЗ после возобновления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='check_after_temp_stop_refuse',
            field=models.BooleanField(default=False, verbose_name='Требуется проверка отказа после возобновления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='check_preliminary_ez',
            field=models.BooleanField(default=False, verbose_name='Требуется проверка первичного ЭЗ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='check_preliminary_refuse',
            field=models.BooleanField(default=False, verbose_name='Требуется проверка первичного отказа'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='check_preliminary_temp_stop',
            field=models.BooleanField(default=False, verbose_name='Требуется проверка приостановки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='common_check_needed',
            field=models.BooleanField(default=False, verbose_name='Требуется общая проверка'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_sent_register_notification',
            field=models.BooleanField(default=False, verbose_name='Отправка уведомления на почту при регистрации'),
        ),
    ]
