# Generated by Django 3.2.8 on 2021-12-02 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211130_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
